version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    resource_class: large
    steps:
      - setup_remote_docker
      - run:
          name: Placeholder Step
          command: |
            # Add your command here
            echo holla
