version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker version
      - run:
          name: docker build
          command: docker build --platform linux/arm64 .
