version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    resource_class: large
    steps:
      - run:
          name: Placeholder Step
          command: |
            # Add your command here
            echo holla
