version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    resource_class: medium
    steps:
      - setup_remote_docker
      - run: 
          name: Update Docker 
          command: |
            sudo apt-get update && \
            sudo apt-get remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin && \
            curl -fsSL https://get.docker.com -o get-docker.sh && \
            sudo sh get-docker.sh || true && \
            sudo apt-get install -y docker-buildx-plugin || true && \
            docker version && \
            docker buildx version
      - run:
          name: Placeholder Step
          command: |
            # Add your command here
            echo holla
