version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build . --platform=linux/arm64
