version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker buildx build --platform linux/arm64 .
