version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    resource_class: medium
    steps:
      - setup_remote_docker
      - run: |
          sudo apt-get update && \
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin && \
          curl -fsSL https://get.docker.com -o get-docker.sh && \
          sudo sh get-docker.sh && \
          sudo apt-get update && \
          sudo apt-get install --upgrade -y docker-buildx-plugin && \
          docker version && \
          docker buildx version
      - run:
          name: Placeholder Step
          command: |
            # Add your command here
            echo holla
