version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    resource_class: medium
    steps:
      - setup_remote_docker
      - run: docker version && docker buildx version
      - run: |
          sudo apt-get update
          sudo apt-get install --upgrade docker-buildx-plugin
          docker buildx version
      - run:
          name: Placeholder Step
          command: |
            # Add your command here
            echo holla
